### ISSUE TITLE
Return result struct instead of parser

### ISSUE THREAD

**Issue by jrester** [ammit/go-metaparser#2]
Wouldn't it be better to return a result object from `ParseHTML` instead of the full parser. Normally you want to only pass around the result of the parse operation and not the whole parser.

**Comment by ammit** [comment]
@jrester The original intention behind keeping it this way was to allow the user to construct their own structs as per their needs, as I thought most of the time user will not need the entire parsed data.

But, we can have a separate method that returns the entire parsed object, If you got time can you work on the PR for same?

**Comment by jrester** [comment]
@ammit Yea, I will implemented it and send you a PR.
